// Generated by gencpp from file jaco_fk/FKCheckResponse.msg
// DO NOT EDIT!


#ifndef JACO_FK_MESSAGE_FKCHECKRESPONSE_H
#define JACO_FK_MESSAGE_FKCHECKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jaco_fk
{
template <class ContainerAllocator>
struct FKCheckResponse_
{
  typedef FKCheckResponse_<ContainerAllocator> Type;

  FKCheckResponse_()
    : in_collision(false)  {
    }
  FKCheckResponse_(const ContainerAllocator& _alloc)
    : in_collision(false)  {
  (void)_alloc;
    }



   typedef uint8_t _in_collision_type;
  _in_collision_type in_collision;





  typedef boost::shared_ptr< ::jaco_fk::FKCheckResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jaco_fk::FKCheckResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FKCheckResponse_

typedef ::jaco_fk::FKCheckResponse_<std::allocator<void> > FKCheckResponse;

typedef boost::shared_ptr< ::jaco_fk::FKCheckResponse > FKCheckResponsePtr;
typedef boost::shared_ptr< ::jaco_fk::FKCheckResponse const> FKCheckResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jaco_fk::FKCheckResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jaco_fk::FKCheckResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jaco_fk

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jaco_fk::FKCheckResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jaco_fk::FKCheckResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jaco_fk::FKCheckResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jaco_fk::FKCheckResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jaco_fk::FKCheckResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jaco_fk::FKCheckResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jaco_fk::FKCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "386d400a9b9180bf5b31ccc793f8e539";
  }

  static const char* value(const ::jaco_fk::FKCheckResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x386d400a9b9180bfULL;
  static const uint64_t static_value2 = 0x5b31ccc793f8e539ULL;
};

template<class ContainerAllocator>
struct DataType< ::jaco_fk::FKCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jaco_fk/FKCheckResponse";
  }

  static const char* value(const ::jaco_fk::FKCheckResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jaco_fk::FKCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool in_collision\n\
\n\
";
  }

  static const char* value(const ::jaco_fk::FKCheckResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jaco_fk::FKCheckResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.in_collision);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FKCheckResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jaco_fk::FKCheckResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jaco_fk::FKCheckResponse_<ContainerAllocator>& v)
  {
    s << indent << "in_collision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.in_collision);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JACO_FK_MESSAGE_FKCHECKRESPONSE_H
